"""Add Module 7 Verification Models

Revision ID: 2696110c250a
Revises: 
Create Date: 2026-07-08 14:19:45.152308
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2696110c250a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('correlation_id', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.BigInteger(), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_action_type'), 'action_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_logs_channel_id'), 'action_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_action_logs_correlation_id'), 'action_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_action_logs_created_at'), 'action_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_logs_executor_id'), 'action_logs', ['executor_id'], unique=False)
    op.create_index(op.f('ix_action_logs_guild_id'), 'action_logs', ['guild_id'], unique=False)
    op.create_index(op.f('ix_action_logs_target_id'), 'action_logs', ['target_id'], unique=False)
    op.create_table('dashboard_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_audit_logs_action'), 'dashboard_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_dashboard_audit_logs_correlation_id'), 'dashboard_audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_dashboard_audit_logs_guild_id'), 'dashboard_audit_logs', ['guild_id'], unique=False)
    op.create_index(op.f('ix_dashboard_audit_logs_timestamp'), 'dashboard_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_dashboard_audit_logs_user_id'), 'dashboard_audit_logs', ['user_id'], unique=False)
    op.create_table('dashboard_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_members_discord_user_id'), 'dashboard_members', ['discord_user_id'], unique=False)
    op.create_index(op.f('ix_dashboard_members_guild_id'), 'dashboard_members', ['guild_id'], unique=False)
    op.create_table('guild_configs',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Cached guild name'),
    sa.Column('icon_hash', sa.String(length=64), nullable=True, comment='Cached guild icon hash'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment="Guild owner's Discord ID"),
    sa.Column('member_count', sa.Integer(), nullable=False, comment='Cached member count'),
    sa.Column('mod_log_channel_id', sa.BigInteger(), nullable=True, comment='Channel for moderation action logs'),
    sa.Column('server_log_channel_id', sa.BigInteger(), nullable=True, comment='Channel for server event logs (joins, leaves, edits)'),
    sa.Column('message_log_channel_id', sa.BigInteger(), nullable=True, comment='Channel for message edit/delete logs'),
    sa.Column('welcome_channel_id', sa.BigInteger(), nullable=True, comment='Channel for welcome messages'),
    sa.Column('verification_channel_id', sa.BigInteger(), nullable=True, comment='Channel for verification panel'),
    sa.Column('suggestion_channel_id', sa.BigInteger(), nullable=True, comment='Channel for suggestion submissions'),
    sa.Column('ticket_category_id', sa.BigInteger(), nullable=True, comment='Category under which ticket channels are created'),
    sa.Column('ticket_log_channel_id', sa.BigInteger(), nullable=True, comment='Channel for ticket transcripts'),
    sa.Column('mute_role_id', sa.BigInteger(), nullable=True, comment='Muted role ID (for legacy mute, timeout is preferred)'),
    sa.Column('verified_role_id', sa.BigInteger(), nullable=True, comment='Role assigned upon verification'),
    sa.Column('auto_role_id', sa.BigInteger(), nullable=True, comment='Role auto-assigned on join'),
    sa.Column('welcome_message', sa.Text(), nullable=True, comment='Welcome message template with {user}, {server}, {count} placeholders'),
    sa.Column('welcome_dm_message', sa.Text(), nullable=True, comment='DM welcome message template'),
    sa.Column('leave_message', sa.Text(), nullable=True, comment='Leave message template'),
    sa.Column('welcome_enabled', sa.Boolean(), nullable=False, comment='Whether welcome messages are enabled'),
    sa.Column('locale', sa.String(length=10), nullable=False, comment='Guild locale for localized messages'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='Guild timezone for scheduled events'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='Discord snowflake ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('executor_id', sa.BigInteger(), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('rollback_status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_incidents_guild_id'), 'security_incidents', ['guild_id'], unique=False)
    op.create_table('security_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_snapshots_guild_id'), 'security_snapshots', ['guild_id'], unique=False)
    op.create_table('verification_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('verification_type', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('moderator_id', sa.BigInteger(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_history_guild_id'), 'verification_history', ['guild_id'], unique=False)
    op.create_index(op.f('ix_verification_history_result'), 'verification_history', ['result'], unique=False)
    op.create_index(op.f('ix_verification_history_timestamp'), 'verification_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_verification_history_user_id'), 'verification_history', ['user_id'], unique=False)
    op.create_table('verification_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('verification_type', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('expected_answer', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_sessions_expires_at'), 'verification_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_verification_sessions_guild_id'), 'verification_sessions', ['guild_id'], unique=False)
    op.create_index(op.f('ix_verification_sessions_session_id'), 'verification_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_verification_sessions_user_id'), 'verification_sessions', ['user_id'], unique=False)
    op.create_table('verification_settings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('verification_type', sa.String(length=20), nullable=False),
    sa.Column('quarantine_role_id', sa.BigInteger(), nullable=True),
    sa.Column('verified_role_id', sa.BigInteger(), nullable=True),
    sa.Column('temporary_role_id', sa.BigInteger(), nullable=True),
    sa.Column('verification_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('risk_threshold_high', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('custom_embed_json', sa.JSON(), nullable=True),
    sa.Column('delete_failed_messages', sa.Boolean(), nullable=False),
    sa.Column('kick_on_timeout', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('guild_module_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False, comment='FK to guild_configs'),
    sa.Column('module_name', sa.String(length=50), nullable=False, comment="Module identifier (e.g., 'automod', 'security', 'welcome')"),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this module is enabled for the guild'),
    sa.Column('config', sa.JSON(), server_default='{}', nullable=False, comment='Module-specific configuration as JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guild_premiums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False, comment='FK to guild_configs'),
    sa.Column('tier', sa.String(length=20), nullable=False, comment='Premium tier: free, basic, pro, enterprise'),
    sa.Column('activated_by', sa.BigInteger(), nullable=False, comment='Discord user ID who activated premium'),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False, comment='When premium was activated'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When premium expires (null = lifetime)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether premium is currently active'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('member_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False, comment='Guild this member data belongs to'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='Discord user ID'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Cached username'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='Cached display/nickname'),
    sa.Column('is_muted', sa.Boolean(), nullable=False, comment='Whether member is currently muted'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether member has completed verification'),
    sa.Column('total_warnings', sa.Integer(), nullable=False, comment='Running total of active warnings'),
    sa.Column('total_messages', sa.Integer(), nullable=False, comment='Total messages sent in this guild (for analytics)'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Moderator notes about this member'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_member_data_guild_user', 'member_data', ['guild_id', 'user_id'], unique=True)
    op.create_table('mod_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False, comment='Guild where the action occurred'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment="Target user's Discord ID"),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False, comment='Moderator or bot user ID who performed the action'),
    sa.Column('action_type', sa.String(length=30), nullable=False, comment='Action type from ModActionType enum'),
    sa.Column('reason', sa.Text(), nullable=False, comment='Reason for the action'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Duration in seconds (for timeouts, mutes)'),
    sa.Column('details', sa.Text(), nullable=True, comment='Additional details (e.g., number of messages purged)'),
    sa.Column('is_automated', sa.Boolean(), nullable=False, comment='Whether this action was triggered by auto-moderation'),
    sa.Column('member_data_id', sa.Integer(), nullable=True, comment='FK to member_data for relationship'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_data_id'], ['member_data.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mod_actions_created', 'mod_actions', ['created_at'], unique=False)
    op.create_index('ix_mod_actions_guild_type', 'mod_actions', ['guild_id', 'action_type'], unique=False)
    op.create_index('ix_mod_actions_guild_user', 'mod_actions', ['guild_id', 'user_id'], unique=False)
    op.create_table('warnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False, comment='Guild where the warning was issued'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment="Warned user's Discord ID"),
    sa.Column('moderator_id', sa.BigInteger(), nullable=False, comment='Moderator who issued the warning'),
    sa.Column('reason', sa.Text(), nullable=False, comment='Warning reason'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this warning is still active'),
    sa.Column('pardoned_by', sa.BigInteger(), nullable=True, comment='Moderator who pardoned/cleared this warning'),
    sa.Column('pardoned_at', sa.DateTime(timezone=True), nullable=True, comment='When the warning was pardoned'),
    sa.Column('member_data_id', sa.Integer(), nullable=True, comment='FK to member_data for cascading deletes'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_data_id'], ['member_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_warnings_guild_user', 'warnings', ['guild_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_warnings_guild_user', table_name='warnings')
    op.drop_table('warnings')
    op.drop_index('ix_mod_actions_guild_user', table_name='mod_actions')
    op.drop_index('ix_mod_actions_guild_type', table_name='mod_actions')
    op.drop_index('ix_mod_actions_created', table_name='mod_actions')
    op.drop_table('mod_actions')
    op.drop_index('ix_member_data_guild_user', table_name='member_data')
    op.drop_table('member_data')
    op.drop_table('guild_premiums')
    op.drop_table('guild_module_settings')
    op.drop_table('verification_settings')
    op.drop_index(op.f('ix_verification_sessions_user_id'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_session_id'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_guild_id'), table_name='verification_sessions')
    op.drop_index(op.f('ix_verification_sessions_expires_at'), table_name='verification_sessions')
    op.drop_table('verification_sessions')
    op.drop_index(op.f('ix_verification_history_user_id'), table_name='verification_history')
    op.drop_index(op.f('ix_verification_history_timestamp'), table_name='verification_history')
    op.drop_index(op.f('ix_verification_history_result'), table_name='verification_history')
    op.drop_index(op.f('ix_verification_history_guild_id'), table_name='verification_history')
    op.drop_table('verification_history')
    op.drop_index(op.f('ix_security_snapshots_guild_id'), table_name='security_snapshots')
    op.drop_table('security_snapshots')
    op.drop_index(op.f('ix_security_incidents_guild_id'), table_name='security_incidents')
    op.drop_table('security_incidents')
    op.drop_table('guild_configs')
    op.drop_index(op.f('ix_dashboard_members_guild_id'), table_name='dashboard_members')
    op.drop_index(op.f('ix_dashboard_members_discord_user_id'), table_name='dashboard_members')
    op.drop_table('dashboard_members')
    op.drop_index(op.f('ix_dashboard_audit_logs_user_id'), table_name='dashboard_audit_logs')
    op.drop_index(op.f('ix_dashboard_audit_logs_timestamp'), table_name='dashboard_audit_logs')
    op.drop_index(op.f('ix_dashboard_audit_logs_guild_id'), table_name='dashboard_audit_logs')
    op.drop_index(op.f('ix_dashboard_audit_logs_correlation_id'), table_name='dashboard_audit_logs')
    op.drop_index(op.f('ix_dashboard_audit_logs_action'), table_name='dashboard_audit_logs')
    op.drop_table('dashboard_audit_logs')
    op.drop_index(op.f('ix_action_logs_target_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_guild_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_executor_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_created_at'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_correlation_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_channel_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_action_type'), table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###
