"""Add Modules 9 to 12 Models

Revision ID: ca13cfbe5c35
Revises: b9aff498daf1
Create Date: 2026-07-08 15:08:19.391828
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ca13cfbe5c35'
down_revision: Union[str, None] = 'b9aff498daf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autorole_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('target', sa.String(length=20), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autorole_settings_guild_id'), 'autorole_settings', ['guild_id'], unique=False)
    op.create_table('reaction_role_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_roles', sa.Integer(), nullable=False),
    sa.Column('max_roles', sa.Integer(), nullable=False),
    sa.Column('required_roles', sa.JSON(), nullable=False),
    sa.Column('blacklisted_roles', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_role_groups_guild_id'), 'reaction_role_groups', ['guild_id'], unique=False)
    op.create_table('server_backups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_backups_guild_id'), 'server_backups', ['guild_id'], unique=False)
    op.create_table('user_xp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('voice_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_xp_guild_id'), 'user_xp', ['guild_id'], unique=False)
    op.create_index(op.f('ix_user_xp_user_id'), 'user_xp', ['user_id'], unique=False)
    op.create_table('welcome_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('welcome_enabled', sa.Boolean(), nullable=False),
    sa.Column('welcome_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('welcome_message', sa.String(length=2000), nullable=True),
    sa.Column('welcome_image_url', sa.String(length=500), nullable=True),
    sa.Column('goodbye_enabled', sa.Boolean(), nullable=False),
    sa.Column('goodbye_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('goodbye_message', sa.String(length=2000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_welcome_settings_guild_id'), 'welcome_settings', ['guild_id'], unique=True)
    op.create_table('xp_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('remove_on_demotion', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_rewards_guild_id'), 'xp_rewards', ['guild_id'], unique=False)
    op.create_table('xp_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('message_xp_min', sa.Integer(), nullable=False),
    sa.Column('message_xp_max', sa.Integer(), nullable=False),
    sa.Column('message_cooldown_sec', sa.Integer(), nullable=False),
    sa.Column('voice_xp_per_minute', sa.Integer(), nullable=False),
    sa.Column('ignored_channels', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_settings_guild_id'), 'xp_settings', ['guild_id'], unique=True)
    op.create_table('reaction_role_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('emoji', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['reaction_role_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction_role_panels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['reaction_role_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reaction_role_panels_guild_id'), 'reaction_role_panels', ['guild_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reaction_role_panels_guild_id'), table_name='reaction_role_panels')
    op.drop_table('reaction_role_panels')
    op.drop_table('reaction_role_items')
    op.drop_index(op.f('ix_xp_settings_guild_id'), table_name='xp_settings')
    op.drop_table('xp_settings')
    op.drop_index(op.f('ix_xp_rewards_guild_id'), table_name='xp_rewards')
    op.drop_table('xp_rewards')
    op.drop_index(op.f('ix_welcome_settings_guild_id'), table_name='welcome_settings')
    op.drop_table('welcome_settings')
    op.drop_index(op.f('ix_user_xp_user_id'), table_name='user_xp')
    op.drop_index(op.f('ix_user_xp_guild_id'), table_name='user_xp')
    op.drop_table('user_xp')
    op.drop_index(op.f('ix_server_backups_guild_id'), table_name='server_backups')
    op.drop_table('server_backups')
    op.drop_index(op.f('ix_reaction_role_groups_guild_id'), table_name='reaction_role_groups')
    op.drop_table('reaction_role_groups')
    op.drop_index(op.f('ix_autorole_settings_guild_id'), table_name='autorole_settings')
    op.drop_table('autorole_settings')
    # ### end Alembic commands ###
